Feat to response method
sourcetoad/enhanced-resources pull request #15
Opened 2020-06-26 01:01 UTC by Jasonej

2020-06-26 14:04 UTC, joeladam518 approved these changes

2020-06-29 13:13 UTC, iBotPeaches approved these changes

2020-07-30 13:32 UTC, iBotPeaches requested changes
Apologies for spam. Testing a deny, then back to approval.

2020-07-30 13:32 UTC, iBotPeaches approved these changes

2020-09-01 19:34 UTC, Jasonej commented
Closing this until I can loop back to it.

2020-09-01 19:34 UTC, closed without merging